services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: medicationplan_test
    ports:
      - "5432:5432"

  app:
    image: eduard124/medicationplan:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
